version: '3.5'

services:
  go-rest-postgres-dev:
    image: postgres:12.1
    container_name: go-rest-postgres-dev
    restart: on-failure
    env_file:
      - ../../env.development
    ports:
      - ${GO_REST_DB_EXTERNAL_PORT}:${GO_REST_DB_PORT}
    environment:
      - POSTGRES_USER=${GO_REST_DB_USER}
      - POSTGRES_PASSWORD=${GO_REST_DB_PASSWORD}
      - POSTGRES_DB=${GO_REST_DB_NAME}
      - POSTGRES_HOST=${GO_REST_DB_HOST}
    volumes:
      - go-rest-volume-postgres-dev:/var/lib/postgresql/data

volumes:
  go-rest-volume-postgres-dev: